/**
 * Scientific paper export, research brief generation, and UI label formatting utilities.
 * 
 * Provides client-side helpers to format paper summaries, transform GraphRAG answers
 * into markdown research briefs, and sanitize entity labels for canvas rendering.
 */

/**
 * Format paper details into structured Markdown for clipboard copying or download.
 *
 * @param {Object} paper - Paper record containing title, authors, abstract, etc.
 * @returns {string} Formatted Markdown representation.
 */
export function formatPaperSummaryMarkdown(paper) {
  if (!paper) return "";

  const title = paper.title || "Untitled Paper";
  const authors = Array.isArray(paper.authors) && paper.authors.length > 0
    ? paper.authors.join(", ")
    : "Unknown Authors";
  const year = paper.publication_year ? ` (${paper.publication_year})` : "";
  const doi = paper.doi ? `\n**DOI**: [${paper.doi}](https://doi.org/${paper.doi})` : "";
  const abstract = paper.abstract || "No abstract available.";

  let entitySection = "";
  if (Array.isArray(paper.entities) && paper.entities.length > 0) {
    const entityList = paper.entities.map(e => `\`${e.name || e}\``).join(", ");
    entitySection = `\n\n### Extracted Scientific Entities\n${entityList}`;
  }

  return `# ${title}\n**Authors**: ${authors}${year}${doi}\n\n### Abstract\n${abstract}${entitySection}\n`;
}

/**
 * Generate a comprehensive research brief from a GraphRAG synthesis result.
 *
 * @param {string} query - The researcher's scientific question.
 * @param {string} answer - Synthesized response from Gemma.
 * @param {Array<Object>} evidenceChunks - List of cited evidence passages.
 * @returns {string} Formatted research brief.
 */
export function generateResearchBriefText(query, answer, evidenceChunks = []) {
  const timestamp = new Date().toISOString().split("T")[0];
  let brief = `# Scientific Research Brief: ${query || "Query"}\n`;
  brief += `*Generated by Insight Weaver on ${timestamp}*\n\n`;
  brief += `## Synthesis\n${answer || "No synthesis available."}\n\n`;

  if (evidenceChunks && evidenceChunks.length > 0) {
    brief += `## Grounding Evidence Chunks (${evidenceChunks.length})\n`;
    evidenceChunks.forEach((chunk, idx) => {
      const section = chunk.section ? ` [Section: ${chunk.section}]` : "";
      brief += `\n### Evidence [${idx + 1}]${section}\n`;
      brief += `> ${chunk.text || chunk.content || "Passage text"}\n`;
    });
  }

  return brief;
}

/**
 * Sanitize and truncate entity or node labels for canvas rendering.
 *
 * @param {string} label - Raw label string.
 * @param {number} maxLength - Maximum allowable length.
 * @returns {string} Truncated clean label.
 */
export function sanitizeNodeLabel(label, maxLength = 28) {
  if (!label) return "";
  const trimmed = String(label).trim();
  if (trimmed.length <= maxLength) return trimmed;
  return `${trimmed.slice(0, maxLength - 3)}...`;
}

// ==============================================================================
// UNUSED FUNCTIONS / DEAD CODE CANDIDATES FOR DEAD CODE ANALYSIS TESTING
// ==============================================================================

/**
 * [UNUSED] Internal hash calculation for deterministic color generation.
 *
 * Dead code note: Uncalled local function inside the module.
 */
function _unusedInternalColorHash(entityType) {
  if (!entityType) return 0;
  let hash = 0;
  for (let i = 0; i < entityType.length; i++) {
    hash = (hash << 5) - hash + entityType.charCodeAt(i);
    hash |= 0;
  }
  return hash;
}

/**
 * [UNUSED] Format a paper object into a raw single-line BibTeX string.
 *
 * Dead code note: Standalone export that is never imported or invoked
 * anywhere in the React UI components.
 */
export function formatLegacyBibtexRaw(paper) {
  if (!paper || !paper.title) return "";
  const key = (paper.title || "").replace(/[^a-zA-Z0-9]/g, "").slice(0, 12).toLowerCase();
  const authors = Array.isArray(paper.authors) ? paper.authors.join(" and ") : "Unknown";
  return `@article{${key}, title={${paper.title}}, author={${authors}}, year={${paper.publication_year || 2024}}}`;
}

/**
 * [UNUSED] Estimate paper reading time in minutes based on raw word count.
 *
 * Dead code note: UI feature planned for paper library card view, but never
 * wired up or referenced in main.jsx or any component.
 */
export function calculateReadingTimeMinutes(wordCount, wordsPerMinute = 200) {
  if (!wordCount || wordCount <= 0) return 0;
  return Math.ceil(wordCount / wordsPerMinute);
}
